export const MEDIA_GENRE_OPTIONS = [
  "news",
  "interview",
  "documentary",
  "research video",
  "drama / fiction",
  "advertising / promo",
  "music video",
  "stand-up / performance",
  "vlog",
  "explainer / commentary",
  "livestream / talk-to-camera",
  "podcast video",
  "reaction video",
  "tutorial / how-to",
  "short-form social clip",
  "meme / remix / edit",
  "archive / found footage",
  "institutional / campaign / public information",
  "webconferencing / meetings / webcalls",
  "other / mixed",
] as const;

export const MEDIA_SUBGENRE_OPTIONS: Record<string, string[]> = {
  news: [
    "breaking news",
    "studio anchor read",
    "field report",
    "panel discussion",
    "investigative segment",
  ],
  interview: [
    "studio interview",
    "field interview",
    "profile interview",
    "vox pop",
    "interrogative interview",
  ],
  documentary: [
    "tv documentary",
    "observational documentary",
    "explanatory documentary",
    "participatory documentary",
    "archival documentary",
    "docudrama",
    "biography documentary",
    "music documentary",
    "science documentary",
  ],
  "research video": [
    "experiment recording",
    "research interview",
    "counseling session",
    "fieldnotes video",
    "observation session",
    "lab demonstration",
  ],
  "drama / fiction": [
    "comedy",
    "tragedy",
    "suspense / thriller",
    "romance",
    "horror",
    "parody / satire",
    "epic / historical",
    "action / adventure",
    "crime / detective",
    "sci-fi",
    "fantasy",
    "melodrama",
  ],
  "advertising / promo": [
    "commercial spot",
    "brand film",
    "product demo",
    "campaign promo",
    "teaser",
  ],
  "music video": [
    "performance clip",
    "narrative clip",
    "lyric video",
    "live session",
    "dance-driven clip",
  ],
  "stand-up / performance": [
    "stand-up set",
    "monologue",
    "stage sketch",
    "spoken word",
    "live act",
  ],
  vlog: [
    "daily vlog",
    "personal update",
    "travel vlog",
    "confessional vlog",
    "family vlog",
  ],
  "explainer / commentary": [
    "explainer",
    "commentary",
    "essay video",
    "analysis breakdown",
    "news commentary",
  ],
  "livestream / talk-to-camera": [
    "solo livestream",
    "chat stream",
    "creator monologue",
    "Q&A stream",
    "event stream",
  ],
  "podcast video": [
    "studio podcast",
    "remote podcast",
    "panel podcast",
    "interview podcast",
    "video essay conversation",
  ],
  "reaction video": [
    "live reaction",
    "duet / stitch reaction",
    "commentary reaction",
    "trailer reaction",
    "watch-along reaction",
  ],
  "tutorial / how-to": [
    "screen tutorial",
    "hands-on demo",
    "step-by-step guide",
    "lesson",
    "workshop",
  ],
  "short-form social clip": [
    "short skit",
    "trend clip",
    "micro-vlog",
    "promo clip",
    "highlight snippet",
  ],
  "meme / remix / edit": [
    "remix",
    "supercut",
    "meme edit",
    "mashup",
    "found-audio edit",
  ],
  "archive / found footage": [
    "newsreel",
    "advertisement archive",
    "newscast archive",
    "news archive",
    "home video archive",
    "surveillance clip",
    "historical footage",
    "recovered media",
  ],
  "institutional / campaign / public information": [
    "press conference",
    "campaign message",
    "public information notice",
    "ceremonial address",
    "organizational briefing",
  ],
  "webconferencing / meetings / webcalls": [
    "team meeting",
    "webinar",
    "remote interview",
    "panel call",
    "classroom session",
  ],
  "other / mixed": ["hybrid format", "unclear / mixed genre", "other"],
};

export const SITUATIONAL_GENRE_OPTIONS = [
  "briefing",
  "confrontation",
  "celebration",
  "mourning",
  "negotiation",
  "confession",
  "testimony",
  "instruction",
  "debate",
  "interview",
  "announcement",
  "emergency response",
  "intimate interaction",
  "routine coordination",
  "leisure / socializing",
  "performance / entertainment",
  "travel / mobility",
  "personal care / inner life",
] as const;

export const SITUATIONAL_SUBGENRE_OPTIONS: Record<string, string[]> = {
  briefing: [
    "press briefing",
    "status update",
    "organizational briefing",
    "explainer briefing",
  ],
  confrontation: [
    "argument",
    "interrogation",
    "accusation",
    "disciplinary exchange",
  ],
  celebration: ["party", "ceremony", "congratulation", "festive gathering"],
  mourning: ["memorial", "condolence", "grief response", "funeral-related scene"],
  negotiation: ["bargaining", "mediation", "diplomatic exchange", "decision-making"],
  confession: ["apology", "disclosure", "emotional admission", "private confession"],
  testimony: ["witness account", "statement to authority", "interview testimony", "documentary testimony"],
  instruction: ["tutorial", "coaching", "classroom instruction", "procedural guidance"],
  debate: ["formal debate", "panel debate", "argumentative exchange", "cross-talk"],
  interview: ["profile interview", "investigative interview", "webcall interview", "vox pop"],
  announcement: ["public announcement", "internal update", "launch reveal", "policy statement"],
  "emergency response": [
    "crisis briefing",
    "rescue coordination",
    "urgent public warning",
    "on-scene response",
  ],
  "intimate interaction": [
    "romantic exchange",
    "family intimacy",
    "emotional support",
    "making love",
  ],
  "routine coordination": ["meeting", "scheduling", "teamwork", "administrative coordination"],
  "leisure / socializing": ["hanging out", "chatting", "public leisure", "game / pastime"],
  "performance / entertainment": ["performance", "rehearsal", "stand-up", "musical moment"],
  "travel / mobility": ["commute", "transit update", "journey segment", "arrival / departure"],
  "personal care / inner life": [
    "grooming",
    "self-talk",
    "reflection",
    "therapeutic / self-care moment",
  ],
};

export const PRIVACY_AXIS_OPTIONS = [
  "public",
  "semi-public",
  "private",
] as const;

export const EXPERTISE_AXIS_OPTIONS = [
  "professional",
  "mixed professional-lay",
  "lay / non-professional",
] as const;

export function getMediaSubgenreOptions(genre: string): string[] {
  return MEDIA_SUBGENRE_OPTIONS[genre] || [];
}

export function getSituationalSubgenreOptions(genre: string): string[] {
  return SITUATIONAL_SUBGENRE_OPTIONS[genre] || [];
}
